# -*- coding: utf-8 -*-
"""TamidProj3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12t-hYL00Rj6KcjdSAYoOuIvaMDNNe43Z
"""

import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt

airports_df = pd.read_csv("airports.csv")
airports_df

airports_df.dropna()
df1 = airports_df.loc[airports_df['AIRPORT'].str.contains("Airport") & airports_df['COUNTRY'].str.contains("USA")]
df1



df2 = df1[['AIRPORT', 'CITY', 'STATE', 'COUNTRY', 'LATITUDE', 'LONGITUDE']]
df2

df3 = df2[['LATITUDE', 'LONGITUDE']]
df3.corr()

df3.plot()