# -*- coding: utf-8 -*-
"""TamidProj2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wOW-pIcjOTvHRWKYpmsT6-DYEHG39tar
"""

import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt

airports_df = pd.read_csv("airports.csv")
airports_df

df2 = airports_df[['IATA_CODE', 'AIRPORT', 'STATE', 'COUNTRY']]
df2

crosstab1 = pd.crosstab(airports_df["LATITUDE"], airports_df["LONGITUDE"])
crosstab1

describedf = airports_df.describe()
describedf

max_df = 71.285450
max_df

airports_df.boxplot(column=["LATITUDE", "LONGITUDE"])

df3 = airports_df[['AIRPORT']]
df3

df3.to_csv("smal")