# -*- coding: utf-8 -*-
"""TamidProj1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BStBJ34rAIQw8WZUS47FwNwUQjeZweWo
"""

import json
import csv
import pandas as pd
import numpy as np

with open('tamidproject1.json') as json_file:
    data = json.load(json_file)
activity_data = data['Players']
data_file = open('tamid1.csv', 'w')
csv_writer = csv.writer(data_file)
csv_writer.writerow(activity_data[0].keys())
for data in activity_data:
    csv_writer.writerow(data.values())
data_file.close()

df = pd.read_csv('tamid1.csv')
df

list_of_names = df['Name'].to_list()
print(list_of_names)